---
- hosts: all
  become: yes
  tasks:
   - name: i am creating first yamal file
     apt:
      name: apache2
      state: present
   - name: i want to install tree
     apt:
      name: tree
      state: present
  when: ansible_os_family= "Debian"  